name: polish-masses
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - scrapy
  - gunicorn
  - flask
  - pip:
    - lxml
    - tldextract
    - requests
    - beautifulsoup4
    - python-google-places
    - jsonlines
    - ipdb
    - colorama
    - html2text
    - binaryornot
