name: polish-masses
channels:
  - defaults
dependencies:
  - python
  - scrapy
  - gunicorn
  - flask
  - redis-py
  - lxml
  - requests
  - beautifulsoup4
  - colorama
  - pip:
    - tldextract
    - python-google-places
    - jsonlines
    - ipdb
    - html2text
    - binaryornot
